version: 2.1
jobs:
  build:
    resource_class: macos.m1.medium.gen1
    macos:
      xcode: "14.2.0"
    steps:
      - checkout
      - run: git clone git@github.com:openslide/openslide.git override/openslide
      - run: brew install meson ninja gawk flock
      - run: brew uninstall git pcre2 xz
      - run: ./build.sh -mmac-arm64 -p main bdist
      - run: |
          pushd openslide-mac-arm64-main 
          echo "otool -L lib/libopenslide.dylib"
          otool -L lib/libopenslide.dylib
          popd
      - store_artifacts:
          path: openslide-mac-arm64-main.tar.gz

workflows:
  version: 2
  build:
    jobs:
      - build
