name: Publish release to SciJava Maven

on: 
  workflow_dispatch:
    inputs:
      openslide_version:
        description: Semantic version of openslide binaries to download.
        type: string
        default: "4.0.0.6"
        required: true

jobs:
  jars:
    name: Build jars
    uses: ./.github/workflows/jars.yml
    with:
      openslide_version: inputs.openslide_version
  publish:
    needs: jars
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/download-artifact@v4
      with:
        merge-multiple: true  

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

    - name: Publish snapshot
      uses: gradle/gradle-build-action@v2.4.2
      with:
        arguments: publish -P release=true -P openslide_version=${{ inputs.openslide_version }}
      env:
        MAVEN_USER: ${{ secrets.MAVEN_USER }}
        MAVEN_PASS: ${{ secrets.MAVEN_PASS }}

